apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "demo-crm.fullname" . }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "demo-crm.selectorLabels" . | nindent 6 }}