{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.ops.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
  annotations:
    description: {{ .Values.serviceAccount.ops.description | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.admin.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-crm.labels" . | nindent 4 }}
  annotations:
    description: {{ .Values.serviceAccount.admin.description | quote }}
automountServiceAccountToken: false
{{- end }}