apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: devops-demo-crm-prod
type: Opaque
stringData:
  mongodb-root-password: "5335332r"   # root user password
  mongodb-passwords: "5335332r"        # app user password
  mongodb-replica-set-key: "jFgSfxp6If7uOG0SIPbShfXDjebKbuv4Q11fMNInpS8="  # shared key between replica members for auth