---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-uri-secret
  namespace: devops-demo-crm-prod
spec:
  encryptedData:
    MONGODB_URI: AgB/y2p2Bwuup5SeVNHUHX8awG2XEGNDHAzsgOF3BxtYOgs116C5CDS1kASuS7PuTCVJV1jzCvZiINFdFZjBoa7xWyEXAXQhZYRoWsO3tUGyHPwREkQaSo+dZ2sQ5hDfoAlOwb5yMn8Z1ScISiSIOIlbhZbMcAFbLyToiPM5tb0D3C+m1iBZZS/UNbvuXQvn9q1d6UkSOG2jPrZn8cmDraUKP2UNwmrlA37ZQSkWACodsJCsq7WahN/eI+5cczXR8dY5/NY6QDRWUuU3ai12/hiD83ckvUYr5WlZ8eWik7/1PwiW9qsC0GdZT9ogWKkVFv/86HuGZxh3swq3tAd4tjc7QDq0cDhZcSqNDWdeJJkUwN2rhXX5wV8X/D5tjok9hQ56Y17otxlDrkyueqeUY5lDDgUTP4iT82bCi5OLkFfEh9CXVbOxBgQWeJ1B16wSstCYJ9ASJOjuzsC5i3fzHC5C0sVxGwBrPr93By3y2IqRHlIxVuH/2c8PsaNOz8eYLASTPDjqjp664tTR+pn/viSnTTb3oayBhJ3FvHNnsEXuaf2gpKlPxGLtp9Ua/6W8m7iBVQXQc7DXoa4bgSMMOuUX/ElgdB5zXoj21omngqUb92KlggBG4C5BO8tIdHEk9Cmt5QWwI11LMlpk/dbRD5tNmvAjqnC1JC/63D5eLy755cyy0lwqP6gkqF7lgsRppcEKPkB3hRvoS1YelsN4BRyIzALI1AWyXLRyCp3SJvh15zE40u0ZS5Fq+V2E2E4D/AfZjT/WuA07YiVCnTjCqhyPdYuqgx3UXtwrvslS7D44jBKkjdOdv2VLzyL/Xf1Im9SwYZAxiy+k0waDqTZKxy/ZJdNCTgR3rD20f7r2ahXi5Z8XJwYMImqKpFIdEzqRqBIvwZr5YA1nJ9W3T4XtA8DoDuhh2hU3PAd4wDkGrDqXvXisOluA7NUXdgcj0vQ5e2HAsjcPRAqXMw==
  template:
    metadata:
      name: mongodb-uri-secret
      namespace: devops-demo-crm-prod
    type: Opaque
