apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri-secret
  namespace: devops-demo-crm-prod
type: Opaque
stringData:
  MONGODB_URI: "mongodb://root:5335332r@mongodb-0.mongodb-headless.devops-demo-crm-prod.svc.cluster.local:27017,mongodb-1.mongodb-headless.devops-demo-crm-prod.svc.cluster.local:27017/?replicaSet=rs0&authSource=admin"
  # mongodb://root:5335332r@mongodb-headless:27017/?replicaSet=rs0&authSource=admin